name: Deploy Jobcircus

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to server
      run: |
        echo "100.25.158.180 ssh-rsa ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNsjyAzerXVocISsqG5xPGmmBCJXn7dsSyCS9nppjChGgNk+HTqqxzSpQnrE4ZeWIPwq+D5IQmrvR1IuL404qHxv4cR0/4i7ZQF1JM9PhfzJkT8iBUsEcppjm1YC2IP/+KR7XDeCceW5SoBRY67z582O2F4nEHv8XH2kE9BCbifUpafnKMcW4FqqU8zVWEYkKF2CdcJxDpX2xdmx39V226PmnwpWHL3bq01R+fR5if+HFXQIlrUNQIrTuX2qxcGZUIQWBxyMffKM/UfT1da6WT3LMCmdIbay7HH2nL5mOY16IAsv4KpPLFn2eW+j1pewLrvKJfiCinkJQDDIrNZ8mqad/xf5Dx9BbZGg0qf8FeJ/8VlhtWPdO+3KuDlscZbacNLLNw7LFaeoS/OMYswN5WeP2dGCQUjrXOy7w9XLgvaYtCGsqBPR4ZUkZ2axfkVNSZcdmvPkBGaNWZbCGWq7J80gElrZ/SCwS+DM/9kAMCzvAZzn8BHDmxWg5xg03LkUk= root@9ea58564e4ea" >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_KEY_PRIVATE }}" > ssh_key.pem
        chmod 600 ssh_key.pem
        ssh -i ssh_key.pem ubuntu@100.25.158.180 'cd /home/ubuntu/jc/job_circus && git pull origin master'
        echo "JobCircus for Life!!!"

